apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exos
  name: flask-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate # pas de cohabitation entre l'ancienne version (révision) et la nouvelle lors d'une mise à jour
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      name: flask-pod
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: opusidea/visits:v1
          env:
          - name: REDIS_HOST
            value: redis-svc # hostaname (DNS) du service associé au déploiment redis

---

apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: exos
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 8080
      targetPort: 8080 # notre application Flash écoute le port 8080
      nodePort: 30009