version: '3'

services:
  redis:
    image: 'redis:5'
  app:
    build: .
    ports:
      - "3200:8080"
    environment:
      - REDIS_HOST=redis
    volumes:
      - app:/usr/src/app

# configuration des volumes
volumes:
  app:


